import stdio
import sys
from markov_model import markov_model

# Takes two integers k and T as command-line arguments, reads the input text
# from standard input and builds a Markov model of order k from the input
# text; then, starting with the k-gram consisting of the first k characters
# of the input text, prints out T characters generated by simulating a
# trajectory through the corresponding Markov chain.


def main():
    k = int(sys.argv[1])
    T = int(sys.argv[2])
    text = sys.stdin.read()
    kgram = text[:k]
    model = markov_model(text, k)
    print model.gen(kgram, T)

if __name__ == '__main__':
    main()
